# Generated by Django 3.2.3 on 2021-06-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(max_length=120)),
                ('created', models.DateField()),
                ('headerImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
