# Generated by Django 3.2.3 on 2021-06-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
